name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: generate puzzle
      run: ./tools/generate_puzzle.sh
    - name: compile
      run: ./tools/compile.sh
    - name: test
      run: ./tools/test.sh
    - name: clean
      run: ./tools/clean.sh
